//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.RE
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Автоматизация.
    /// </summary>
    // *** Start programmer edit section *** (Автоматизация CustomAttributes)

    // *** End programmer edit section *** (Автоматизация CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АвтоматизацияE", new string[] {
            "Номер as \'Номер\'"})]
    [AssociatedDetailViewAttribute("АвтоматизацияE", "Покупка", "ПокупкаE", true, "", "Покупка", true, new string[] {
            ""})]
    [View("АвтоматизацияL", new string[] {
            "Номер as \'Номер\'"})]
    [AssociatedDetailViewAttribute("АвтоматизацияL", "Покупка", "ПокупкаL", true, "", "Покупка", true, new string[] {
            ""})]
    public class Автоматизация : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.RE.DetailArrayOfПокупка fПокупка;
        
        // *** Start programmer edit section *** (Автоматизация CustomMembers)

        // *** End programmer edit section *** (Автоматизация CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Автоматизация.Номер CustomAttributes)

        // *** End programmer edit section *** (Автоматизация.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Автоматизация.Номер Get start)

                // *** End programmer edit section *** (Автоматизация.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Автоматизация.Номер Get end)

                // *** End programmer edit section *** (Автоматизация.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Автоматизация.Номер Set start)

                // *** End programmer edit section *** (Автоматизация.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Автоматизация.Номер Set end)

                // *** End programmer edit section *** (Автоматизация.Номер Set end)
            }
        }
        
        /// <summary>
        /// Автоматизация.
        /// </summary>
        // *** Start programmer edit section *** (Автоматизация.Покупка CustomAttributes)

        // *** End programmer edit section *** (Автоматизация.Покупка CustomAttributes)
        public virtual IIS.RE.DetailArrayOfПокупка Покупка
        {
            get
            {
                // *** Start programmer edit section *** (Автоматизация.Покупка Get start)

                // *** End programmer edit section *** (Автоматизация.Покупка Get start)
                if ((this.fПокупка == null))
                {
                    this.fПокупка = new IIS.RE.DetailArrayOfПокупка(this);
                }
                IIS.RE.DetailArrayOfПокупка result = this.fПокупка;
                // *** Start programmer edit section *** (Автоматизация.Покупка Get end)

                // *** End programmer edit section *** (Автоматизация.Покупка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Автоматизация.Покупка Set start)

                // *** End programmer edit section *** (Автоматизация.Покупка Set start)
                this.fПокупка = value;
                // *** Start programmer edit section *** (Автоматизация.Покупка Set end)

                // *** End programmer edit section *** (Автоматизация.Покупка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АвтоматизацияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АвтоматизацияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АвтоматизацияE", typeof(IIS.RE.Автоматизация));
                }
            }
            
            /// <summary>
            /// "АвтоматизацияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АвтоматизацияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АвтоматизацияL", typeof(IIS.RE.Автоматизация));
                }
            }
        }
    }
}
