//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.RE
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// База клиента.
    /// </summary>
    // *** Start programmer edit section *** (БазаКлиента CustomAttributes)

    // *** End programmer edit section *** (БазаКлиента CustomAttributes)
    [AutoAltered()]
    [Caption("База клиента")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БазаКлиентаE", new string[] {
            "IdКлиента as \'Id клиента\'",
            "Логин as \'Логин\'",
            "Пароль as \'Пароль\'",
            "НомерКарта as \'Номер карта\'"})]
    [View("БазаКлиентаL", new string[] {
            "IdКлиента as \'Id клиента\'",
            "Логин as \'Логин\'",
            "Пароль as \'Пароль\'",
            "НомерКарта as \'Номер карта\'"})]
    public class БазаКлиента : ICSSoft.STORMNET.DataObject
    {
        
        private int fIdКлиента;
        
        private string fЛогин;
        
        private string fПароль;
        
        private int fНомерКарта;
        
        // *** Start programmer edit section *** (БазаКлиента CustomMembers)

        // *** End programmer edit section *** (БазаКлиента CustomMembers)

        
        /// <summary>
        /// IdКлиента.
        /// </summary>
        // *** Start programmer edit section *** (БазаКлиента.IdКлиента CustomAttributes)

        // *** End programmer edit section *** (БазаКлиента.IdКлиента CustomAttributes)
        public virtual int IdКлиента
        {
            get
            {
                // *** Start programmer edit section *** (БазаКлиента.IdКлиента Get start)

                // *** End programmer edit section *** (БазаКлиента.IdКлиента Get start)
                int result = this.fIdКлиента;
                // *** Start programmer edit section *** (БазаКлиента.IdКлиента Get end)

                // *** End programmer edit section *** (БазаКлиента.IdКлиента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазаКлиента.IdКлиента Set start)

                // *** End programmer edit section *** (БазаКлиента.IdКлиента Set start)
                this.fIdКлиента = value;
                // *** Start programmer edit section *** (БазаКлиента.IdКлиента Set end)

                // *** End programmer edit section *** (БазаКлиента.IdКлиента Set end)
            }
        }
        
        /// <summary>
        /// Логин.
        /// </summary>
        // *** Start programmer edit section *** (БазаКлиента.Логин CustomAttributes)

        // *** End programmer edit section *** (БазаКлиента.Логин CustomAttributes)
        [StrLen(255)]
        public virtual string Логин
        {
            get
            {
                // *** Start programmer edit section *** (БазаКлиента.Логин Get start)

                // *** End programmer edit section *** (БазаКлиента.Логин Get start)
                string result = this.fЛогин;
                // *** Start programmer edit section *** (БазаКлиента.Логин Get end)

                // *** End programmer edit section *** (БазаКлиента.Логин Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазаКлиента.Логин Set start)

                // *** End programmer edit section *** (БазаКлиента.Логин Set start)
                this.fЛогин = value;
                // *** Start programmer edit section *** (БазаКлиента.Логин Set end)

                // *** End programmer edit section *** (БазаКлиента.Логин Set end)
            }
        }
        
        /// <summary>
        /// НомерКарта.
        /// </summary>
        // *** Start programmer edit section *** (БазаКлиента.НомерКарта CustomAttributes)

        // *** End programmer edit section *** (БазаКлиента.НомерКарта CustomAttributes)
        public virtual int НомерКарта
        {
            get
            {
                // *** Start programmer edit section *** (БазаКлиента.НомерКарта Get start)

                // *** End programmer edit section *** (БазаКлиента.НомерКарта Get start)
                int result = this.fНомерКарта;
                // *** Start programmer edit section *** (БазаКлиента.НомерКарта Get end)

                // *** End programmer edit section *** (БазаКлиента.НомерКарта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазаКлиента.НомерКарта Set start)

                // *** End programmer edit section *** (БазаКлиента.НомерКарта Set start)
                this.fНомерКарта = value;
                // *** Start programmer edit section *** (БазаКлиента.НомерКарта Set end)

                // *** End programmer edit section *** (БазаКлиента.НомерКарта Set end)
            }
        }
        
        /// <summary>
        /// Пароль.
        /// </summary>
        // *** Start programmer edit section *** (БазаКлиента.Пароль CustomAttributes)

        // *** End programmer edit section *** (БазаКлиента.Пароль CustomAttributes)
        [StrLen(255)]
        public virtual string Пароль
        {
            get
            {
                // *** Start programmer edit section *** (БазаКлиента.Пароль Get start)

                // *** End programmer edit section *** (БазаКлиента.Пароль Get start)
                string result = this.fПароль;
                // *** Start programmer edit section *** (БазаКлиента.Пароль Get end)

                // *** End programmer edit section *** (БазаКлиента.Пароль Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазаКлиента.Пароль Set start)

                // *** End programmer edit section *** (БазаКлиента.Пароль Set start)
                this.fПароль = value;
                // *** Start programmer edit section *** (БазаКлиента.Пароль Set end)

                // *** End programmer edit section *** (БазаКлиента.Пароль Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БазаКлиентаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БазаКлиентаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БазаКлиентаE", typeof(IIS.RE.БазаКлиента));
                }
            }
            
            /// <summary>
            /// "БазаКлиентаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БазаКлиентаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БазаКлиентаL", typeof(IIS.RE.БазаКлиента));
                }
            }
        }
    }
}
