//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.RE
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Остаток.
    /// </summary>
    // *** Start programmer edit section *** (Остаток CustomAttributes)

    // *** End programmer edit section *** (Остаток CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОстатокE", new string[] {
            "Номер as \'Номер\'",
            "Колво as \'Колво\'"})]
    [View("ОстатокL", new string[] {
            "Номер as \'Номер\'",
            "Колво as \'Колво\'"})]
    public class Остаток : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private double fКолво;
        
        // *** Start programmer edit section *** (Остаток CustomMembers)

        // *** End programmer edit section *** (Остаток CustomMembers)

        
        /// <summary>
        /// Колво.
        /// </summary>
        // *** Start programmer edit section *** (Остаток.Колво CustomAttributes)

        // *** End programmer edit section *** (Остаток.Колво CustomAttributes)
        public virtual double Колво
        {
            get
            {
                // *** Start programmer edit section *** (Остаток.Колво Get start)

                // *** End programmer edit section *** (Остаток.Колво Get start)
                double result = this.fКолво;
                // *** Start programmer edit section *** (Остаток.Колво Get end)

                // *** End programmer edit section *** (Остаток.Колво Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Остаток.Колво Set start)

                // *** End programmer edit section *** (Остаток.Колво Set start)
                this.fКолво = value;
                // *** Start programmer edit section *** (Остаток.Колво Set end)

                // *** End programmer edit section *** (Остаток.Колво Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Остаток.Номер CustomAttributes)

        // *** End programmer edit section *** (Остаток.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Остаток.Номер Get start)

                // *** End programmer edit section *** (Остаток.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Остаток.Номер Get end)

                // *** End programmer edit section *** (Остаток.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Остаток.Номер Set start)

                // *** End programmer edit section *** (Остаток.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Остаток.Номер Set end)

                // *** End programmer edit section *** (Остаток.Номер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОстатокE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОстатокE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОстатокE", typeof(IIS.RE.Остаток));
                }
            }
            
            /// <summary>
            /// "ОстатокL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОстатокL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОстатокL", typeof(IIS.RE.Остаток));
                }
            }
        }
    }
}
