//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.RE
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Резервуар.
    /// </summary>
    // *** Start programmer edit section *** (Резервуар CustomAttributes)

    // *** End programmer edit section *** (Резервуар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РезервуарE", new string[] {
            "КолвоТоп as \'Колво топ\'",
            "Состояние as \'Состояние\'",
            "IdР as \'Id Р\'"})]
    [View("РезервуарL", new string[] {
            "КолвоТоп as \'Колво топ\'",
            "Состояние as \'Состояние\'",
            "IdР as \'Id Р\'"})]
    public class Резервуар : ICSSoft.STORMNET.DataObject
    {
        
        private double fКолвоТоп;
        
        private IIS.RE.Состояния fСостояние;
        
        private int fIdР;
        
        private IIS.RE.Остаток fОстаток;
        
        // *** Start programmer edit section *** (Резервуар CustomMembers)

        // *** End programmer edit section *** (Резервуар CustomMembers)

        
        /// <summary>
        /// IdР.
        /// </summary>
        // *** Start programmer edit section *** (Резервуар.IdР CustomAttributes)

        // *** End programmer edit section *** (Резервуар.IdР CustomAttributes)
        public virtual int IdР
        {
            get
            {
                // *** Start programmer edit section *** (Резервуар.IdР Get start)

                // *** End programmer edit section *** (Резервуар.IdР Get start)
                int result = this.fIdР;
                // *** Start programmer edit section *** (Резервуар.IdР Get end)

                // *** End programmer edit section *** (Резервуар.IdР Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Резервуар.IdР Set start)

                // *** End programmer edit section *** (Резервуар.IdР Set start)
                this.fIdР = value;
                // *** Start programmer edit section *** (Резервуар.IdР Set end)

                // *** End programmer edit section *** (Резервуар.IdР Set end)
            }
        }
        
        /// <summary>
        /// КолвоТоп.
        /// </summary>
        // *** Start programmer edit section *** (Резервуар.КолвоТоп CustomAttributes)

        // *** End programmer edit section *** (Резервуар.КолвоТоп CustomAttributes)
        public virtual double КолвоТоп
        {
            get
            {
                // *** Start programmer edit section *** (Резервуар.КолвоТоп Get start)

                // *** End programmer edit section *** (Резервуар.КолвоТоп Get start)
                double result = this.fКолвоТоп;
                // *** Start programmer edit section *** (Резервуар.КолвоТоп Get end)

                // *** End programmer edit section *** (Резервуар.КолвоТоп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Резервуар.КолвоТоп Set start)

                // *** End programmer edit section *** (Резервуар.КолвоТоп Set start)
                this.fКолвоТоп = value;
                // *** Start programmer edit section *** (Резервуар.КолвоТоп Set end)

                // *** End programmer edit section *** (Резервуар.КолвоТоп Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Резервуар.Состояние CustomAttributes)

        // *** End programmer edit section *** (Резервуар.Состояние CustomAttributes)
        public virtual IIS.RE.Состояния Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Резервуар.Состояние Get start)

                // *** End programmer edit section *** (Резервуар.Состояние Get start)
                IIS.RE.Состояния result = this.fСостояние;
                // *** Start programmer edit section *** (Резервуар.Состояние Get end)

                // *** End programmer edit section *** (Резервуар.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Резервуар.Состояние Set start)

                // *** End programmer edit section *** (Резервуар.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Резервуар.Состояние Set end)

                // *** End programmer edit section *** (Резервуар.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Резервуар.
        /// </summary>
        // *** Start programmer edit section *** (Резервуар.Остаток CustomAttributes)

        // *** End programmer edit section *** (Резервуар.Остаток CustomAttributes)
        [PropertyStorage(new string[] {
                "Остаток"})]
        [NotNull()]
        public virtual IIS.RE.Остаток Остаток
        {
            get
            {
                // *** Start programmer edit section *** (Резервуар.Остаток Get start)

                // *** End programmer edit section *** (Резервуар.Остаток Get start)
                IIS.RE.Остаток result = this.fОстаток;
                // *** Start programmer edit section *** (Резервуар.Остаток Get end)

                // *** End programmer edit section *** (Резервуар.Остаток Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Резервуар.Остаток Set start)

                // *** End programmer edit section *** (Резервуар.Остаток Set start)
                this.fОстаток = value;
                // *** Start programmer edit section *** (Резервуар.Остаток Set end)

                // *** End programmer edit section *** (Резервуар.Остаток Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РезервуарE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РезервуарE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РезервуарE", typeof(IIS.RE.Резервуар));
                }
            }
            
            /// <summary>
            /// "РезервуарL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РезервуарL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РезервуарL", typeof(IIS.RE.Резервуар));
                }
            }
        }
    }
}
