//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.RE
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ценновая стела.
    /// </summary>
    // *** Start programmer edit section *** (ЦенноваяСтела CustomAttributes)

    // *** End programmer edit section *** (ЦенноваяСтела CustomAttributes)
    [AutoAltered()]
    [Caption("Ценновая стела")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЦенноваяСтелаE", new string[] {
            "Наименование as \'Наименование\'",
            "Цена as \'Цена\'"})]
    [View("ЦенноваяСтелаL", new string[] {
            "Наименование as \'Наименование\'",
            "Цена as \'Цена\'"})]
    public class ЦенноваяСтела : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private double fЦена;
        
        // *** Start programmer edit section *** (ЦенноваяСтела CustomMembers)

        // *** End programmer edit section *** (ЦенноваяСтела CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ЦенноваяСтела.Наименование CustomAttributes)

        // *** End programmer edit section *** (ЦенноваяСтела.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ЦенноваяСтела.Наименование Get start)

                // *** End programmer edit section *** (ЦенноваяСтела.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ЦенноваяСтела.Наименование Get end)

                // *** End programmer edit section *** (ЦенноваяСтела.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЦенноваяСтела.Наименование Set start)

                // *** End programmer edit section *** (ЦенноваяСтела.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ЦенноваяСтела.Наименование Set end)

                // *** End programmer edit section *** (ЦенноваяСтела.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (ЦенноваяСтела.Цена CustomAttributes)

        // *** End programmer edit section *** (ЦенноваяСтела.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (ЦенноваяСтела.Цена Get start)

                // *** End programmer edit section *** (ЦенноваяСтела.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (ЦенноваяСтела.Цена Get end)

                // *** End programmer edit section *** (ЦенноваяСтела.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЦенноваяСтела.Цена Set start)

                // *** End programmer edit section *** (ЦенноваяСтела.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (ЦенноваяСтела.Цена Set end)

                // *** End programmer edit section *** (ЦенноваяСтела.Цена Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЦенноваяСтелаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЦенноваяСтелаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЦенноваяСтелаE", typeof(IIS.RE.ЦенноваяСтела));
                }
            }
            
            /// <summary>
            /// "ЦенноваяСтелаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЦенноваяСтелаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЦенноваяСтелаL", typeof(IIS.RE.ЦенноваяСтела));
                }
            }
        }
    }
}
